### ISSUE TITLE
Client application failed to make a policy decision

### ISSUE THREAD

**Issue by rgbworld** [PaddleHQ/Mac-Framework-V4#19]
Paddle 4.0.2
Xcode: 10.0
macOS: 10.14

When attempting to checkout via `paddle.showCheckout(for:)`, I am receiving the following error: 

**On macOS 10.14, the error is:**
"Client application failed to make a policy decision via WebPolicyDecisionListener, using defaultPolicy 2".

The error occurs immediately after `willShowPaddle(_:product:)` is executed by the SDK. Within the `willShowPaddle` function, `uiType` appears to correct and is logged as `.checkout.` 

The `PADCheckoutStateCompletion`  block is never reached.

Is this a policy setup issue in my project or an SDK issue?

**macOS 10.13.6:**
Using Paddle 4.0.2, Xcode 10 and macOS 10.13.6, I am having a similar issues after attempting to checkout via `paddle.showCheckout(for:)`:

The problem on macOS 10.13.6 is that within `didDismissPaddle(_:triggeredUIType:product:)`, `uiType = .checkout`, however, `triggeredUIType = .cancel`.

So, I am getting `.cancel` as a result at the same time a _Paddle Alert_ stating "Checkout Complete" is displayed in a separate window in front of the Paddle checkout window . 

![paddle order complete](https://user-images.githubusercontent.com/1319222/46018516-a8da1e00-c09f-11e8-9d02-3ab8225764e7.png)

So, I implemented `willShowPaddle(_ alert: PADAlert)` and returned `false` to prevent the Paddle Alert. After doing that, I updated to macOS 10.14 and I am receiving the `WebPolicyDecisionListener` error posted above.

Note: I am using Paddle for checkout only. DevMateKit is used for licensing and activation/trial. So all I need is to handle the the checkout response, however, the completion block is not called, so it seems like an SDK issue.

Thank you for any advice or confirmation of these issues.

**Comment by GregularExpressions** [comment]
Hey @rgbworld 

Thanks for the report, the 10.14 issue should be resolved as of Friday's [v4.0.3 Release](https://github.com/PaddleHQ/Mac-Framework-V4/releases/tag/v4.0.3).

We'll look into the 10.13 problem you describe.

Thanks,
Greg.

**Comment by GregularExpressions** [comment]
@rgbworld for the 10.13 issue, can you let us know the productID you were working with an any Product Configuration you set please?

**Comment by rgbworld** [comment]
@GregularExpressions I can confirm that the 10.14 issue (WebPolicyDecisionListener) is fixed in version 4.0.3.

The "10.13" issue is still a problem and affects os 10.13 and 10.14. I have moved the "cancel after success" issue to a separate issue #29

Please see my reply on the new thread.
